#!/usr/bin/env ruby

require "bundler/setup"
require "dayone_toolbox"


class DayoneToolbox::CLI::Journal
  desc "version", "Show version number"
  def version
    puts v = DayoneToolbox::VERSION
  end
end

DayoneToolbox::CLI::Journal.start(ARGV)
